http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    carte:
        paths:
            -   '/api/customer'
            -   '/api/customer/*'
            -   '/api/restaurant'
            -   '/api/restaurant/*'
            -   '/api/courier'
            -   '/api/courier/*'
    file:
        paths:
            -   '/api/file'
            -   '/api/file/*'
            -   '/api/bucket'
            -   '/api/bucket/*'
    location:
        paths:
            -   '/api/location'
    account:
        paths:
            -   '/api/user'
            -   '/api/user/*'
            -   '/api/auth'
            -   '/api/auth/*'
serviceEndpoints:
    carte:
        url: 'http://18.218.61.61:8085'
    account:
        url: 'http://18.218.61.61:8080'
    location:
        url: 'http://18.218.61.61:8083'
    file:
        url: 'http://18.218.61.61:8084'
policies:
    - rewrite
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    default:
        apiEndpoints:
            - api
        policies:
            # Uncomment `key-auth:` when instructed to in the Getting Started guide.
            # - key-auth:
            -   proxy:
                    -   action:
                            serviceEndpoint: httpbin
                            changeOrigin: true

    rainbow:
        apiEndpoints:
            - rainbow
        policies:
            -   rewrite:
                    -   condition:
                            name: regexpmatch
                            match: ^/api/([^/]+)(.*)$
                        action:
                            rewrite: /$2
            -   log:
                    -   action:
                            message: ${req.hostname} ${req.ip || req.connection.remoteAddress} - [${new Date().toLocaleString()}] "${req.method} ${req.originalUrl} ~> ${req.url} HTTP/${req.httpVersion}" ${res.statusCode} "${req.headers['user-agent']}"
            -   rate-limit:
                    -   action:
                            max: 10
                            windowMs: 60000
                            headers: true
            -   proxy:
                    -   action:
                            serviceEndpoint: rainbow
                            changeOrigin: true
